name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up go toolchain
        uses: action/setup-go@v5

      - name: build pro
        run: ./scripts/buildprod.sh
